# Server configurations
server:
  connection_string: mongodb://localhost:27017

# Database credentials
database:
  user: "root"
  pass: "root"

# Logging level: trace, debug, info, warn, error, fatal, panic
loglevel:
  level: "info"
