openapi: 3.0.1
info:
  contact:
    email: lukasz.dudzinski@ovoo.pl
  title: Discrepancy Service API
  description: This is the REST API specification for the Discrepancy Service
  version: 0.0.1
servers:
  - url: /api/v1/
tags:
- description: Access to usage discrepancy
  name: usage
- description: Access to settlement discrepancy
  name: settlement
    
paths:
  /usages/{usageId}:
    put:
      summary: Request usage discrepancy
      description: Request usage discrepancy   
      operationId: calculateUsageDiscrepancy
      parameters:        
        - name: usageId
          in: path
          description: home usage report ID
          required: true
          schema:
            type: string
        - name: partnerUsageId
          in: query
          description: partner usage report ID
          required: true
          schema:
            type: string
      requestBody:
        description: Home & partner usage reports
        required: true
        content:
          application/json: {
            schema: {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Usage"
                },
                "minItems": 2,
                "maxItems": 2
            }
          }
        
      responses:
        '200':
          description: Discrepancy report with inbound and outbound details
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/UsageDiscrepancyReport'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /usages/:              
    get:
      summary: Returns all pets
      operationId: findUsages
      
      responses:
        '200':
          description: Discrepancy report with home and partner perscpective
          content:
            application/json:
              schema: 
                $ref: '#/components/schemas/Usage'
        
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
                
  /settlements/{settlementId}:
    put:
      summary: Request settlement discrepancy
      description: Request settlement discrepancy   
      operationId: calculateSettlementDiscrepancy
      parameters:        
        - name: settlementId
          in: path
          description: home settlement ID
          required: true
          schema:
            type: string
        - name: partnerSettlementId
          in: query
          description: partner settlement ID
          required: true
          schema:
            type: string
      requestBody:
        description: Home & partner settlements
        required: true
        content:
          application/json: {
            schema: {
                "type": "array",
                "items": {
                    "$ref": "#/components/schemas/Settlement"
                },
                "minItems": 2,
                "maxItems": 2
            }
          } 
      responses:
        '200':
          description: Discrepancy report with home and partner perscpectives
          content:
            application/json:
              schema:
                  $ref: '#/components/schemas/SettlementDiscrepancyReport'
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  
  
  
components:
  schemas:
    
    Usage:
      required:
        - header
        - body
      properties:
        header:
          required:
            - version
            - type
            - context
          type: object
          description: Usage header
          properties:
            version:
              type: string
              description: Version of the document type
            type:
              type: string
              description: Type of the document
            mspOwner:
              type: string
              description: MSP owner
            context:
              type: string
              description: Context
        body:
          required:
            - inbound
            - outbound
          type: object
          description: Body of the Usage type object
          properties:
            inbound:
              type: array
              items: 
                $ref: '#/components/schemas/UsageData'
            outbound:
              type: array
              items: 
                $ref: '#/components/schemas/UsageData'
    UsageData:
      properties:
        yearMonth:
          type: string
        homeTadig:
          type: string
        visitorTadig:
          type: string
        service:
          type: string
        usage:
          type: number
          format: double
        units:
          type: string
    Error:
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
          description: Error code
        message:
          type: string
          description: Error message
    
    GeneralInfoData:
      required:
        - service
        - unit
        - inbound_own_usage
        - inbound_partner_usage
        - inbound_discrepancy
        - outbound_own_usage
        - outbound_partner_usage
        - outbound_discrepancy
      properties:
        service:
          type: string
        unit:
          type: string
        inbound_own_usage:
          type: number
          format: double
        inbound_partner_usage:
          type: number
          format: double
        inbound_discrepancy:
          type: number
          format: double
        outbound_own_usage:
          type: number
          format: double
        outbound_partner_usage:
          type: number
          format: double
        outbound_discrepancy:
          type: number
          format: double
    
    UsageDiscrepancyData:
      properties:
        HTMN:
          type: string
        VPMN:
          type: string
        yearMonth:
          type: string
        service:
          type: string
        own_usage:
          type: number
          format: double
        partner_usage:
          type: number
          format: double
        delta_usage_abs:
          type: number
          format: double
        delta_usage_percent:
          type: number
          format: double
              
    UsageDiscrepancyReport:
      properties:
        general_information:
          type: array
          items: 
            $ref: '#/components/schemas/GeneralInfoData'
        inbound:
          type: array
          items: 
            $ref: '#/components/schemas/UsageDiscrepancyData'
        outbound:
          type: array
          items: 
            $ref: '#/components/schemas/UsageDiscrepancyData'
    
    Settlement:
      required:
        - header
        - body
      properties:
        header:
          type: object
          description: Settlement header
          required:
            - version
            - type
            - mspOwner
            - context
          properties:
            version:
              type: string
              description: Version of the document type
            type:
              type: string
              description: Type of the document
            mspOwner:
              type: string
              description: MSP owner
            context:
              type: string
              description: Context
        body:
          type: object
          description: Settlement body
          required:
            - inbound
            - outbound
          properties:
            fromdate:
              type: string
            todate:
              type: string
            inbound:
              type: object
              $ref: '#/components/schemas/SettlementServices'
            outbound:
              type: object
              $ref: '#/components/schemas/SettlementServices'
    
    SettlementServices:
        type: object
        required:
          - currency
          - services
        properties:
            currency:
              type: string
            services:
              type: object
              required:
                - voice
                - SMS
                - data
              properties:
                voice:
                  type: object
                  properties:
                    MOC:
                      type: object
                      $ref: '#/components/schemas/MOC'  
                    MTC:
                      type: number
                      format: double
                SMS:
                  type: object
                  properties:
                    MO:
                      type: number
                      format: double
                    MT:
                      type: number
                      format: double
                data:
                  type: array
                  items: 
                    $ref: '#/components/schemas/DataService'
                  
    DataService:
      type: object
      properties:
        name:
          type: string
        value:
          type: number
          format: double
    
    MOC:
      type: object
      properties:
        local:
          type: number
          format: double
        backHome:
          type: number
          format: double
        international:
          type: number
          format: double
        premium:
          type: number
          format: double
        ROW:
          type: number
          format: double
        specialDestinations:
          type: number
          format: double
        international:
          type: number
          format: double
    
    SettlementDiscrepancyReport:
      type: object
      properties:
        homePerspective:
          type: object
          required:
            - general_information
            - details
          properties:
            general_information:
              type: array
              items: 
                $ref: '#/components/schemas/SettlementDiscrepancyRecord'
            details:
              type: array
              items: 
                $ref: '#/components/schemas/SettlementDiscrepancyRecord'
        partnerPerspective:
          type: object
          required:
            - general_information
            - details
          properties:
            general_information:
              type: array
              items: 
                $ref: '#/components/schemas/SettlementDiscrepancyRecord'
            details:
              type: array
              items: 
                $ref: '#/components/schemas/SettlementDiscrepancyRecord'
                
    SettlementDiscrepancyRecord:
      required:
        - service
        - unit
        - own_usage
        - partner_usage
        - delta_usage_abs
        - delta_usage_percent
        - own_calculation
        - partner_calculation
        - delta_calculation_percent
      properties:
        service:
          type: string
        unit:
          type: string
        own_usage:
          type: number
          format: double
        partner_usage:
          type: number
          format: double
        delta_usage_abs:
          type: number
          format: double
        delta_usage_percent:
          type: number
          format: double
        own_calculation:
          type: number
          format: double
        partner_calculation:
          type: number
          format: double
        delta_calculation_percent:
          type: number
          format: double
          